routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\InstituteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
Route::get('/', function () {
    return view('welcome');
});
*/
Route::get('/', [App\Http\Controllers\HomeController::class, 'portada'])->name('/');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resources([
    'institute' => InstituteController::class,
]);

app/Models/Institute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Institute extends Model
{
    use HasFactory;

    protected $fillable = [
        'officialName', 'name', 'shortName', 'img', 'logo', 'slogan', 'email', 'phone', 'phone2', 'phone3', 'address', 'support', 'website', 'active'

    ];
}

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Institute;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $institute = Institute::all();
        return view('home', compact('institute'));
    }

    public function portada()
    {
        $institute = Institute::all();
        return view('welcome', compact('institute'));
    }
}

app/Http/Controllers/InstituteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Institute;
use Illuminate\Http\Request;

class InstituteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $institute = Institute::all();
        return view('institute.index', compact('institute'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('institute.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $institute = request()->except('_token');

        if ($request->hasFile('img')) {
            $institute['img'] = $request->file('img')->store('imgInstitute', 'public');
        }
        if ($request->hasFile('logo')) {
            $institute['logo'] = $request->file('logo')->store('logoInstitute', 'public');
        }

        Institute::insert($institute);
        return redirect()->to(url('/institute'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Institute  $institute
     * @return \Illuminate\Http\Response
     */
    public function show(Institute $institute)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Institute  $institute
     * @return \Illuminate\Http\Response
     */
    public function edit(Institute $institute)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Institute  $institute
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Institute $institute)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Institute  $institute
     * @return \Illuminate\Http\Response
     */
    public function destroy(Institute $institute)
    {
        //
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Models\Teacher;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function edit(Teacher $teacher)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Teacher $teacher)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Teacher $teacher)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                        @foreach($institute as $inst)
                            <div class="text-center">
                                <h2>{{ $inst->officialName }}</h2>
                                <h3 class="text-green">{{ $inst->name }}</h3>
                                <h3>{{ $inst->slogan }}</h3>
                                <h1 class="text-bold">Sistema de Asesoría Académica</h1>
                            </div>
                        @endforeach
                </div>
            </div>
        </div>
    </div>
</div>


<!-- jQuery -->
<script src="{{ asset('adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('adminlte/plugins/select2/js/select2.full.min.js') }}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{{ asset('adminlte/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js') }}"></script>
<!-- InputMask -->
<script src="{{ asset('adminlte/plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('adminlte/plugins/inputmask/jquery.inputmask.min.js') }}"></script>
<!-- date-range-picker -->
<script src="{{ asset('adminlte/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- bootstrap color picker -->
<script src="{{ asset('adminlte/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Bootstrap Switch -->
<script src="{{ asset('adminlte/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
<!-- BS-Stepper -->
<script src="{{ asset('adminlte/plugins/bs-stepper/js/bs-stepper.min.js') }}"></script>
<!-- dropzonejs -->
<script src="{{ asset('adminlte/plugins/dropzone/min/dropzone.min.js') }}"></script>



@endsection

resources/views/institute/create.blade.php
@extends('layouts.master')

@section('content')

    <div class="card card-primary">
        <div class="card-header">
            <h1 class="card-title"><i class="fas fa-home"></i> Datos de la Institución</h1>
        </div>
        <form action="{{ route('institute.store') }}" method="post">

            @csrf
            <div class="card-body">
                <div class="row">
                    <p>Rellena con la información de tu Institución. Esta información será utilizada para personalizar
                        la
                        identidad del sistema.</p>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
                        <label for="">Nombre oficial: </label>
                        <input class="form-control" type="text" name="officialName" id="" placeholder="Nombre oficial"
                               autofocus
                               required style="text-transform: uppercase">
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
                        <label for="">Nombre: </label>
                        <input class="form-control" type="text" name="name" id="" placeholder="Nombre local" required
                               style="text-transform: uppercase">
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
                        <label for="">Siglas o nombre corto: </label>
                        <input class="form-control" type="text" name="shortName" id=""
                               placeholder="Siglas o nombre corto"
                               required style="text-transform: uppercase">
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-xl-6">
                        <label for="">Imagen para portada: </label>
                        <input class="" type="file" name="img" required accept=".png, .jpeg, .bmp">
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-xl-6">
                        <label for="">Logo: </label>
                        <input class="" type="file" name="logo" required accept=".png, .jpeg, .bmp">
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col">
                        <label for="">Eslogan: </label>
                        <input class="form-control" type="text" name="slogan" id="" placeholder="Eslogan" required>
                    </div>
                </div>
                <br>


                <div class="row">
                    <p>Agrega la información de contacto.</p>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
                        <label for="">Email institucional: </label>
                        <input class="form-control" type="email" name="email" id="" placeholder="Email institucional"
                               required>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
                        <label for="">Teléfono: </label>
                        <input type="text" class="form-control" name="phone"
                               data-inputmask="'mask': ['999-999-9999 [x99999]', '+099 99 99 9999[9]-9999']" data-mask>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4 col-xl-4">
                        <label for="">Sitio web: </label>
                        <input class="form-control" type="url" name="website" placeholder="https://www.example.com"
                               required>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col">
                        <label for="">Dirección: </label>
                        <input class="form-control" type="text" name="address" id="" placeholder="Dirección" required>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col">
                        <label for="">Contacto para recibir soporte: </label>
                        <input class="form-control" type="text" name="support" id="" placeholder="" required>
                    </div>
                </div>

                <br>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <input class="btn btn-info" type="reset" value="Restablecer">
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </div>
            </div>
        </form>

    </div>
    <br><br><br>

    <script>
        $("#telefono").autoNumeric('init', {aSep: ' ', dGroup: '4', mDec: '0'});
    </script>
@endsection

resources/views/institute/index.blade.php
@extends('layouts.master')

@section('content')

    index de instituto

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>